# Generated by Django 4.2 on 2024-10-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsitem_title_alter_newsitem_translated_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='link',
            field=models.TextField(),
        ),
    ]
