# Generated by Django 4.2 on 2024-09-27 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overall_analysis', models.TextField()),
                ('market_analysis', models.TextField()),
                ('chart_analysis', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likers', models.ManyToManyField(related_name='liked_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_weight', models.FloatField(default=1.0)),
                ('market_weight', models.FloatField(default=1.0)),
                ('news_weight', models.FloatField(default=1.0)),
                ('chart_overall_weight', models.FloatField(default=1.0)),
                ('chart_technical_weight', models.FloatField(default=1.0)),
                ('chart_candlestick_weight', models.FloatField(default=1.0)),
                ('chart_moving_average_weight', models.FloatField(default=1.0)),
                ('chart_bollinger_bands_weight', models.FloatField(default=1.0)),
                ('chart_rsi_weight', models.FloatField(default=1.0)),
                ('chart_fibonacci_weight', models.FloatField(default=1.0)),
                ('chart_macd_weight', models.FloatField(default=1.0)),
                ('chart_support_resistance_weight', models.FloatField(default=1.0)),
                ('main_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='reports.mainreport')),
            ],
        ),
        migrations.CreateModel(
            name='NewsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_analysis', models.TextField()),
                ('main_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news_report', to='reports.mainreport')),
            ],
        ),
        migrations.CreateModel(
            name='ChartReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_analysis', models.TextField()),
                ('candlestick_analysis', models.TextField()),
                ('moving_average_analysis', models.TextField()),
                ('bollinger_bands_analysis', models.TextField()),
                ('rsi_analysis', models.TextField()),
                ('fibonacci_retracement_analysis', models.TextField()),
                ('macd_analysis', models.TextField()),
                ('support_resistance_analysis', models.TextField()),
                ('chart_image', models.ImageField(upload_to='chart_images/')),
                ('chart_data', models.JSONField()),
                ('main_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chart_report', to='reports.mainreport')),
            ],
        ),
    ]
