# Generated by Django 4.2 on 2024-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_accuracy_main_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuracy',
            name='recommendation',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('HOLD', 'HOLD')], default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accuracy',
            name='recommendation_value',
            field=models.IntegerField(default=0),
        ),
    ]
