# Generated by Django 4.2 on 2024-09-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_accuracy_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuracy',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accuracy',
            name='price_change',
            field=models.FloatField(default=0),
        ),
    ]
