# Generated by Django 4.2 on 2024-10-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_accuracy_is_correct_accuracy_price_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainreport',
            name='chart_report_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainreport',
            name='news_report_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainreport',
            name='weights_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
